Differentiate README by person-type
BonnyCI/docs pull request #18
Opened 2017-01-18 21:30 UTC by mlangbehn

README.md now has documentation split up by person-type.

Signed-off-by: Matt Langbehn <matthew.langbehn@gmail.com>

2017-01-18 21:34 UTC, eggshell commented
I think we need to have a `getting started` section for both types of people, whereas `contributing` can just stay in the developer section.

2017-01-18 21:35 UTC, mlangbehn commented
@eggshell, yeah, that's why I said "more is needed on this one." I'll add [WIP] to the title.

2017-01-18 21:42 UTC, eggshell commented on README.md
>  Checkout the [getting started](getting_started) section.
This should be check out.

2017-01-19 16:04 UTC, eggshell requested changes

2017-01-19 16:04 UTC, eggshell commented on README.md
> +Check out the [end user](end_users) documentation.
can we make the label and the dir name match up?

2017-01-19 16:04 UTC, eggshell commented on README.md
> +- [End Users](#end-users)
Same as below

2017-01-19 16:04 UTC, eggshell commented on README.md
> +Please see the [developer documentation](developers) for more information.
Same as above. Also, let's keep the labels consistent. For instance, the word documentation is included in the label here but is not in the end user section.

2017-01-19 16:10 UTC, mlangbehn commented on README.md
> +- [End Users](#end-users)
This is a link to the section in this README, not to the end_users section of lore, so no, I do not think this should be made to match the directory name.

2017-01-19 16:10 UTC, mlangbehn commented on README.md
> +Check out the [end user](end_users) documentation.
We can, but I was making the link text more user friendly.

2017-01-19 16:12 UTC, mlangbehn commented on README.md
> +Please see the [developer documentation](developers) for more information.
Same comment as above (making the link text "developers" would make this sentence read poorly). Additionally, including "documentation" in the link text was what I meant to do in both the developer and end user sections.

2017-01-19 16:16 UTC, eggshell commented on README.md
> +Check out the [end user](end_users) documentation.
Fair enough, I hadn't read the sentence for grammatical correctness.

2017-01-19 16:16 UTC, eggshell commented on README.md
> +- [End Users](#end-users)
Fair enough, I hadn't read the sentence for grammatical correctness.

2017-01-19 16:18 UTC, mlangbehn commented on README.md
> +- [End Users](#end-users)
Adding summation of chat @eggshell and I just had:
I believe readability of documentation is paramount. @eggshell agreed.

2017-01-19 16:20 UTC, eggshell approved these changes

2017-01-19 16:51 UTC, eggshell approved these changes

2017-01-19 16:52 UTC, eggshell commented
lgtm

2017-01-19 16:52 UTC, merged