Add design docs section and propose a design
BonnyCI/docs pull request #27
Opened 2017-01-24 19:34 UTC by j2sol

An attempt at using lore for proposing design documents for review.
Putting up
https://github.com/BonnyCI/projman/wiki/GitHub-Pull-Request-Check-and-Gate-Design
as a first proposed design using this method.

Signed-off-by: Jesse Keating <jkeating@j2solutions.net>

2017-01-24 20:05 UTC, ConsoleCatzirl requested changes

2017-01-24 20:05 UTC, ConsoleCatzirl commented on developers/contributing/designs/github-pr-check-gate.md
> +**On failure, Zuul will also comment on the pull request indicating the failure.**
Why is this bold?

2017-01-24 20:05 UTC, ConsoleCatzirl commented on developers/contributing/designs/github-pr-check-gate.md
> +A check pipeline is [http://docs.openstack.org/infra/zuul/zuul.html#pipelines](independent), and tests the change as presented, as if it were merged immediately. The check pipeline will set a commit
This part needs changing: your link syntax for the independent pipeline is reversed, the url should be in the parentheses.

2017-01-24 20:05 UTC, ConsoleCatzirl commented on developers/contributing/designs/github-pr-check-gate.md
> +A gate pipeline is a [DependentPipelineManager](http://docs.openstack.org/infra/zuul/zuul.html#pipelines) which creates a queue of changes to be tested together to be merged. Gate pipelines should be
nit: I'm not sure about the use of "could be merged" here, I would prefer replacing that with either "should be merged" or "is ready to be merged".

2017-01-24 20:05 UTC, jesusaurus commented on developers/contributing/designs/github-pr-check-gate.md
> +**On failure, Zuul will also comment on the pull request indicating the failure.**
Why is this bold?

2017-01-24 20:05 UTC, jesusaurus commented on developers/contributing/designs/github-pr-check-gate.md
> +* **`status` from BonnyCI on HEAD of PR with a state of `success`**
This should mention that the status comes from the check pipeline.

2017-01-24 20:05 UTC, jesusaurus commented on developers/contributing/designs/github-pr-check-gate.md
> +* **`status` from BonnyCI on HEAD of PR with a state of `success`**
This should also mention the check pipeline.

2017-01-24 20:44 UTC, missaugustina requested changes
Right now this isn't very clear and seems pretty disorganized. I'm working on some edits that I'll propose shortly.

2017-01-24 21:07 UTC, omgjlk commented on developers/contributing/designs/github-pr-check-gate.md
> +A check pipeline is [http://docs.openstack.org/infra/zuul/zuul.html#pipelines](independent), and tests the change as presented, as if it were merged immediately. The check pipeline will set a commit
Fixed.

2017-01-24 21:07 UTC, omgjlk commented on developers/contributing/designs/github-pr-check-gate.md
> +A gate pipeline is a [DependentPipelineManager](http://docs.openstack.org/infra/zuul/zuul.html#pipelines) which creates a queue of changes to be tested together to be merged. Gate pipelines should be
Fixed.

2017-01-24 21:07 UTC, omgjlk commented on developers/contributing/designs/github-pr-check-gate.md
> +* **`status` from BonnyCI on HEAD of PR with a state of `success`**
Fixed

2017-01-24 21:07 UTC, omgjlk commented on developers/contributing/designs/github-pr-check-gate.md
> +* **`status` from BonnyCI on HEAD of PR with a state of `success`**
Fixed.

2017-01-24 23:38 UTC, missaugustina commented
I added my edit here - https://github.com/BonnyCI/lore/compare/j2sol-ghi-design-doc

2017-01-25 02:22 UTC, missaugustina approved these changes

2017-01-25 20:28 UTC, mlangbehn reviewed
Just a quick inline question.

2017-01-25 20:28 UTC, mlangbehn commented on developers/contributing/README.md
> +Changes to BonnyCI should follow a design document. To propose a design document, open a pull requests to the lore repository. BonnyCI contributors will review and debate the proposed document via pu
Should the reference to the lore repo be a link?

2017-01-25 20:47 UTC, j2sol commented on developers/contributing/README.md
> +Changes to BonnyCI should follow a design document. To propose a design document, open a pull requests to the lore repository. BonnyCI contributors will review and debate the proposed document via pu
Made it a link.

2017-01-25 21:47 UTC, ConsoleCatzirl approved these changes

2017-01-26 02:20 UTC, merged